import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';
import { PassThrough } from 'node:stream';
import { DatabaseSync } from 'node:sqlite';

import {
  initSchema,
  createUser,
  getUserByEmail,
  createSession,
  rotateUserPassword,
  isValidBcryptHash
} from '../src/db.js';
import { hashPassword, verifyPassword } from '../src/auth.js';
import { promptSecret, run, OperationCancelledError } from '../scripts/rotate-local-user-password.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const TEST_DIR = path.join(__dirname, '..', 'data_test');

// Determine real candidate DB path dynamically without assuming hardcoded locations
const CANDIDATE_REAL_DB = process.env.DB_PATH || path.join(__dirname, '..', 'data', 'sales_flow.db');

if (!fs.existsSync(TEST_DIR)) {
  fs.mkdirSync(TEST_DIR, { recursive: true });
}

function createIsolatedTestDb(dbName) {
  const dbPath = path.join(TEST_DIR, dbName);
  if (fs.existsSync(dbPath)) {
    fs.unlinkSync(dbPath);
  }
  const db = new DatabaseSync(dbPath);
  initSchema(db);
  return { db, dbPath };
}

/**
 * Mock interactive TTY input stream for deterministic testing.
 */
class MockTtyInputStream extends PassThrough {
  constructor() {
    super();
    this.isTTY = true;
    this.isRaw = false;
    this.rawModeHistory = [];
  }

  setRawMode(val) {
    this.isRaw = Boolean(val);
    this.rawModeHistory.push(this.isRaw);
    return this;
  }
}

test('Password Rotation Unit & Transactional Security Suite', async (t) => {
  // Capture initial stat of real candidate DB to verify non-modification
  let initialRealDbStat = null;
  if (fs.existsSync(CANDIDATE_REAL_DB)) {
    initialRealDbStat = fs.statSync(CANDIDATE_REAL_DB);
  }

  await t.test('1. Validación estricta de formato bcrypt (isValidBcryptHash)', async () => {
    // Generar un hash canónico real con bcryptjs
    const validCanonicalHash = await hashPassword('TestValidPassword123!');
    assert.equal(isValidBcryptHash(validCanonicalHash), true, 'Bcrypt hash generated by canonical module must be valid');

    // Hashes válidos con variantes estándar ($2a$, $2b$, $2y$) y longitud exacta 60
    assert.equal(isValidBcryptHash('$2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'), true);
    assert.equal(isValidBcryptHash('$2b$12$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'), true);
    assert.equal(isValidBcryptHash('$2y$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'), true);

    // Casos negativos: cadenas arbitrarias, truncadas, incompletas o malformadas
    assert.equal(isValidBcryptHash(null), false);
    assert.equal(isValidBcryptHash(''), false);
    assert.equal(isValidBcryptHash('$2'), false);
    assert.equal(isValidBcryptHash('$2a$'), false);
    assert.equal(isValidBcryptHash('$2b$10$'), false);
    assert.equal(isValidBcryptHash('$2b$10$short'), false);
    assert.equal(isValidBcryptHash('$2b$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWyEXTRA'), false);
    assert.equal(isValidBcryptHash('PlaintextPassword123!'), false);
    assert.equal(isValidBcryptHash('$3a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy'), false);
  });

  await t.test('2. La contraseña anterior deja de validar y la nueva valida correctamente', async () => {
    const { db, dbPath } = createIsolatedTestDb('rotation_test_2.db');
    try {
      const oldPass = 'OldAdminPassword123!';
      const newPass = 'NewAdminPassword456!';
      const oldHash = await hashPassword(oldPass);

      const user = createUser({
        name: 'Admin Test',
        email: 'admin@rotation-test.local',
        passwordHash: oldHash,
        role: 'ADMIN'
      }, db);

      const initialUser = getUserByEmail(user.email, db);
      assert.equal(await verifyPassword(oldPass, initialUser.password_hash), true);

      const newHash = await hashPassword(newPass);
      const rotationResult = rotateUserPassword({
        email: user.email,
        newPasswordHash: newHash,
        actorUserId: 'LOCAL_MAINTENANCE_CLI'
      }, db);

      assert.equal(rotationResult.email, user.email);
      assert.equal(rotationResult.userId, user.id);

      const updatedUser = getUserByEmail(user.email, db);
      assert.equal(await verifyPassword(oldPass, updatedUser.password_hash), false);
      assert.equal(await verifyPassword(newPass, updatedUser.password_hash), true);
    } finally {
      db.close();
      if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
    }
  });

  await t.test('3. Se revocan todas las sesiones activas del usuario objetivo y se preservan las de otros usuarios', async () => {
    const { db, dbPath } = createIsolatedTestDb('rotation_test_3.db');
    try {
      const userA = createUser({
        name: 'User A',
        email: 'user_a@rotation-test.local',
        passwordHash: await hashPassword('PasswordUserA123!'),
        role: 'ADMIN'
      }, db);

      const userB = createUser({
        name: 'User B',
        email: 'user_b@rotation-test.local',
        passwordHash: await hashPassword('PasswordUserB123!'),
        role: 'OPERATOR'
      }, db);

      // Crear 3 sesiones activas para user A
      createSession({ userId: userA.id, sessionTokenHash: 'hash_a_1' }, db);
      createSession({ userId: userA.id, sessionTokenHash: 'hash_a_2' }, db);
      createSession({ userId: userA.id, sessionTokenHash: 'hash_a_3' }, db);

      // Crear 2 sesiones activas para user B
      createSession({ userId: userB.id, sessionTokenHash: 'hash_b_1' }, db);
      createSession({ userId: userB.id, sessionTokenHash: 'hash_b_2' }, db);

      const rotationResult = rotateUserPassword({
        email: userA.email,
        newPasswordHash: await hashPassword('BrandNewPasswordA123!'),
        actorUserId: 'LOCAL_MAINTENANCE_CLI'
      }, db);

      assert.equal(rotationResult.revokedSessionsCount, 3);

      const activeSessionsA = db.prepare('SELECT * FROM auth_sessions WHERE user_id = ? AND revoked_at IS NULL').all(userA.id);
      assert.equal(activeSessionsA.length, 0);

      const revokedSessionsA = db.prepare('SELECT * FROM auth_sessions WHERE user_id = ? AND revoked_at IS NOT NULL').all(userA.id);
      assert.equal(revokedSessionsA.length, 3);

      const activeSessionsB = db.prepare('SELECT * FROM auth_sessions WHERE user_id = ? AND revoked_at IS NULL').all(userB.id);
      assert.equal(activeSessionsB.length, 2);

      const revokedSessionsB = db.prepare('SELECT * FROM auth_sessions WHERE user_id = ? AND revoked_at IS NOT NULL').all(userB.id);
      assert.equal(revokedSessionsB.length, 0);
    } finally {
      db.close();
      if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
    }
  });

  await t.test('4. Registro append-only en audit_log sin almacenar contraseñas, hashes ni tokens', async () => {
    const { db, dbPath } = createIsolatedTestDb('rotation_test_4.db');
    try {
      const plaintextPassword = 'SecretPlaintextPasswordToNeverLog123!';
      const passwordHash = await hashPassword(plaintextPassword);
      const user = createUser({
        name: 'Audited User',
        email: 'audit@rotation-test.local',
        passwordHash: await hashPassword('InitialPass123!'),
        role: 'OPERATOR'
      }, db);

      createSession({ userId: user.id, sessionTokenHash: 'session_token_hash_secret_value' }, db);

      const rotationResult = rotateUserPassword({
        email: user.email,
        newPasswordHash: passwordHash,
        actorUserId: 'LOCAL_MAINTENANCE_CLI'
      }, db);

      const auditEvents = db.prepare(`
        SELECT * FROM audit_log
        WHERE entity_id = ? AND event_type = 'USER_PASSWORD_ROTATED'
      `).all(user.id);

      assert.equal(auditEvents.length, 1);
      const event = auditEvents[0];

      assert.equal(event.entity_type, 'USER');
      assert.equal(event.entity_id, user.id);
      assert.equal(event.actor_user_id, 'LOCAL_MAINTENANCE_CLI');
      assert.equal(event.id, rotationResult.auditLogId);

      const serializedEvent = JSON.stringify(event);
      assert.equal(serializedEvent.includes(plaintextPassword), false, 'Audit event must NEVER contain plaintext password');
      assert.equal(serializedEvent.includes(passwordHash), false, 'Audit event must NEVER contain password hash');
      assert.equal(serializedEvent.includes('session_token_hash_secret_value'), false, 'Audit event must NEVER contain session token');

      const newState = JSON.parse(event.new_state_json);
      assert.equal(newState.revoked_sessions_count, 1);
      assert.ok(newState.timestamp);
    } finally {
      db.close();
      if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
    }
  });

  await t.test('5. Usuario inexistente o hash inválido produce error y cero mutaciones', async () => {
    const { db, dbPath } = createIsolatedTestDb('rotation_test_5.db');
    try {
      const validHash = await hashPassword('ValidDummyPassword123!');

      // Usuario inexistente
      assert.throws(() => {
        rotateUserPassword({
          email: 'nonexistent@rotation-test.local',
          newPasswordHash: validHash,
          actorUserId: 'LOCAL_MAINTENANCE_CLI'
        }, db);
      }, /not found/i);

      // Hash inválido que empieza con $2 pero está truncado
      assert.throws(() => {
        rotateUserPassword({
          email: 'admin@rotation-test.local',
          newPasswordHash: '$2b$10$truncated',
          actorUserId: 'LOCAL_MAINTENANCE_CLI'
        }, db);
      }, /Valid bcrypt password hash is required/i);

      const auditCount = db.prepare('SELECT COUNT(*) as count FROM audit_log').get();
      assert.equal(auditCount.count, 0);

      const sessionCount = db.prepare('SELECT COUNT(*) as count FROM auth_sessions').get();
      assert.equal(sessionCount.count, 0);
    } finally {
      db.close();
      if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
    }
  });

  await t.test('6. Fallo intermedio revierte atómicamente contraseña, sesiones y auditoría (BEGIN IMMEDIATE)', async () => {
    const { db, dbPath } = createIsolatedTestDb('rotation_test_6.db');
    try {
      const initialPass = 'InitialSafePassword123!';
      const initialHash = await hashPassword(initialPass);
      const user = createUser({
        name: 'Rollback User',
        email: 'rollback@rotation-test.local',
        passwordHash: initialHash,
        role: 'ADMIN'
      }, db);

      createSession({ userId: user.id, sessionTokenHash: 'token_to_remain_active' }, db);

      db.exec(`
        CREATE TRIGGER test_fail_trigger
        BEFORE INSERT ON audit_log
        WHEN NEW.event_type = 'USER_PASSWORD_ROTATED' AND NEW.entity_id = '${user.id}'
        BEGIN
          SELECT RAISE(ABORT, 'Simulated mid-transaction failure');
        END;
      `);

      const newPass = 'NewUncommittedPassword123!';
      const newHash = await hashPassword(newPass);

      assert.throws(() => {
        rotateUserPassword({
          email: user.email,
          newPasswordHash: newHash,
          actorUserId: 'LOCAL_MAINTENANCE_CLI'
        }, db);
      }, /Simulated mid-transaction failure/);

      const userAfterRollback = getUserByEmail(user.email, db);
      assert.equal(userAfterRollback.password_hash, initialHash);
      assert.equal(await verifyPassword(initialPass, userAfterRollback.password_hash), true);

      const activeSession = db.prepare('SELECT * FROM auth_sessions WHERE user_id = ? AND session_token_hash = ?').get(user.id, 'token_to_remain_active');
      assert.equal(activeSession.revoked_at, null);

      const auditRows = db.prepare('SELECT * FROM audit_log WHERE entity_id = ?').all(user.id);
      assert.equal(auditRows.length, 0);
    } finally {
      db.close();
      if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
    }
  });

  await t.test('7. Preservación total de datos comerciales, hechos, borradores y acciones', async () => {
    const { db, dbPath } = createIsolatedTestDb('rotation_test_7.db');
    try {
      const user = createUser({
        name: 'Operator Commercial',
        email: 'commercial@rotation-test.local',
        passwordHash: await hashPassword('InitialPassCommercial123!'),
        role: 'OPERATOR'
      }, db);

      const now = new Date().toISOString();
      const leadId = crypto.randomUUID();
      db.prepare(`
        INSERT INTO leads (id, idempotency_key, text_hash, raw_text, source, status, created_by_user_id, created_at, updated_at)
        VALUES (?, ?, ?, ?, 'MANUAL', 'CONFIRMED', ?, ?, ?)
      `).run(leadId, 'key-commercial-1', 'hash-1', 'Texto comercial de prueba', user.id, now, now);

      const factsId = crypto.randomUUID();
      db.prepare(`
        INSERT INTO lead_confirmed_facts (id, lead_id, version, is_current, request_type, scope_summary, urgency, confirmed_by_user_id, confirmed_at)
        VALUES (?, ?, 1, 1, 'DEMO', 'Demostración de plataforma', 'MEDIUM', ?, ?)
      `).run(factsId, leadId, user.id, now);

      const draftId = crypto.randomUUID();
      db.prepare(`
        INSERT INTO response_drafts (id, lead_id, confirmed_facts_version, model_identifier, prompt_version, initial_draft_text, edited_text, status, reviewed_by_user_id, created_at, updated_at)
        VALUES (?, ?, 1, 'gemini-3.6-flash', 'v1.0', 'Borrador comercial preservado', NULL, 'GENERATED', ?, ?, ?)
      `).run(draftId, leadId, user.id, now, now);

      const actionId = crypto.randomUUID();
      db.prepare(`
        INSERT INTO lead_actions (id, lead_id, assigned_user_id, action_type, description, due_date, status, created_at, updated_at)
        VALUES (?, ?, ?, 'SCHEDULE_DEMO', 'Demostración agendada', ?, 'PENDING', ?, ?)
      `).run(actionId, leadId, user.id, now, now, now);

      rotateUserPassword({
        email: user.email,
        newPasswordHash: await hashPassword('NewCommercialPassword123!'),
        actorUserId: 'LOCAL_MAINTENANCE_CLI'
      }, db);

      const lead = db.prepare('SELECT * FROM leads WHERE id = ?').get(leadId);
      assert.equal(lead.status, 'CONFIRMED');

      const facts = db.prepare('SELECT * FROM lead_confirmed_facts WHERE id = ?').get(factsId);
      assert.equal(facts.is_current, 1);

      const draft = db.prepare('SELECT * FROM response_drafts WHERE id = ?').get(draftId);
      assert.equal(draft.status, 'GENERATED');
      assert.equal(draft.initial_draft_text, 'Borrador comercial preservado');

      const action = db.prepare('SELECT * FROM lead_actions WHERE id = ?').get(actionId);
      assert.equal(action.status, 'PENDING');
      assert.equal(action.assigned_user_id, user.id);
    } finally {
      db.close();
      if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
    }
  });

  await t.test('8. Entrada interactiva de contraseña con TTY simulado (promptSecret)', async (st) => {
    await st.test('A. Entrada carácter a carácter (tecleo normal)', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      let outputBuffer = '';
      mockOutput.on('data', (d) => { outputBuffer += d.toString(); });

      const secretPromise = promptSecret('Prompt: ', { input: mockInput, output: mockOutput });

      // Escribir carácter a carácter
      const chars = ['C', 'l', 'a', 'v', 'e', 'S', 'e', 'g', 'u', 'r', 'a', '1', '2', '3', '!', '\r'];
      for (const ch of chars) {
        mockInput.write(ch);
      }

      const result = await secretPromise;
      assert.equal(result, 'ClaveSegura123!');
      // Validar que la salida solo tiene máscara y prompt, nunca la clave en texto plano
      assert.equal(outputBuffer.includes('ClaveSegura123!'), false);
      assert.equal(outputBuffer.includes('Prompt: ***************\n'), true);
      assert.equal(mockInput.listenerCount('data'), 0, 'data listener must be cleaned up');
    });

    await st.test('B. Contraseña pegada como un único bloque', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      let outputBuffer = '';
      mockOutput.on('data', (d) => { outputBuffer += d.toString(); });

      const secretPromise = promptSecret('Pass: ', { input: mockInput, output: mockOutput });

      // Pegado en bloque sin enter inicial, seguido de Enter
      mockInput.write('PastedPasswordInSingleBlock123!');
      mockInput.write('\n');

      const result = await secretPromise;
      assert.equal(result, 'PastedPasswordInSingleBlock123!');
      assert.equal(outputBuffer.includes('PastedPasswordInSingleBlock123!'), false);
      assert.equal(mockInput.listenerCount('data'), 0);
    });

    await st.test('C. Bloque pegado que incluye contraseña y Enter en un solo chunk', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      let outputBuffer = '';
      mockOutput.on('data', (d) => { outputBuffer += d.toString(); });

      const secretPromise = promptSecret('Pass: ', { input: mockInput, output: mockOutput });

      // Un solo chunk con texto + \r\n
      mockInput.write('InstantPasteWithCRLF123!\r\n');

      const result = await secretPromise;
      assert.equal(result, 'InstantPasteWithCRLF123!');
      assert.equal(outputBuffer.includes('InstantPasteWithCRLF123!'), false);
      assert.equal(mockInput.listenerCount('data'), 0);
    });

    await st.test('D. Tratamiento correcto de Backspace', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      let outputBuffer = '';
      mockOutput.on('data', (d) => { outputBuffer += d.toString(); });

      const secretPromise = promptSecret('Key: ', { input: mockInput, output: mockOutput });

      // Teclear 'a', 'b', 'c', borrar dos caracteres ('\b', '\b'), teclear 'd', luego Enter
      mockInput.write('a');
      mockInput.write('b');
      mockInput.write('c');
      mockInput.write('\b');
      mockInput.write('\u007f'); // backspace alternativo
      mockInput.write('d');
      mockInput.write('\n');

      const result = await secretPromise;
      assert.equal(result, 'ad');
      assert.equal(outputBuffer.includes('ad'), false);
      assert.equal(mockInput.listenerCount('data'), 0);
    });

    await st.test('E. Cancelación con Ctrl+C (rejection limpia, restauración de modo)', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      let outputBuffer = '';
      mockOutput.on('data', (d) => { outputBuffer += d.toString(); });

      const secretPromise = promptSecret('Key: ', { input: mockInput, output: mockOutput });

      mockInput.write('some_partial');
      mockInput.write('\u0003'); // Ctrl+C

      await assert.rejects(async () => {
        await secretPromise;
      }, (err) => {
        assert.ok(err instanceof OperationCancelledError);
        assert.equal(err.isCancelled, true);
        return true;
      });

      assert.equal(outputBuffer.includes('some_partial'), false);
      assert.equal(mockInput.isRaw, false, 'Raw mode must be restored to false on Ctrl+C');
      assert.equal(mockInput.listenerCount('data'), 0);
    });

    await st.test('F. Error de stream durante la lectura (limpieza de listeners)', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();

      const secretPromise = promptSecret('Key: ', { input: mockInput, output: mockOutput });

      mockInput.destroy(new Error('Simulated socket breakdown'));

      await assert.rejects(async () => {
        await secretPromise;
      }, /Simulated socket breakdown/);

      assert.equal(mockInput.listenerCount('data'), 0);
    });
  });

  await t.test('9. Validación de CLI con flujos simulados y no exposición de secretos', async (st) => {
    await st.test('A. Rechazo de contraseñas con longitud menor a 12 caracteres', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      const mockErr = new PassThrough();
      let errText = '';
      mockErr.on('data', (d) => { errText += d.toString(); });

      const { db, dbPath } = createIsolatedTestDb('rotation_cli_1.db');
      try {
        createUser({
          name: 'User Short',
          email: 'short@rotation-test.local',
          passwordHash: await hashPassword('InitialPass123!'),
          role: 'ADMIN'
        }, db);

        const runPromise = run(['node', 'script.js', 'short@rotation-test.local'], {
          input: mockInput,
          output: mockOutput,
          errOutput: mockErr,
          db
        });

        // Ingresar clave corta de 8 caracteres
        mockInput.write('short12!\n');

        const exitCode = await runPromise;
        assert.equal(exitCode, 1);
        assert.match(errText, /al menos 12 caracteres/i);
        assert.equal(errText.includes('short12!'), false, 'Secret must not be in stderr');
      } finally {
        db.close();
        if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
      }
    });

    await st.test('B. Rechazo de contraseñas no coincidentes en confirmación', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      const mockErr = new PassThrough();
      let errText = '';
      mockErr.on('data', (d) => { errText += d.toString(); });

      const { db, dbPath } = createIsolatedTestDb('rotation_cli_2.db');
      try {
        createUser({
          name: 'User Mismatch',
          email: 'mismatch@rotation-test.local',
          passwordHash: await hashPassword('InitialPass123!'),
          role: 'ADMIN'
        }, db);

        const runPromise = run(['node', 'script.js', 'mismatch@rotation-test.local'], {
          input: mockInput,
          output: mockOutput,
          errOutput: mockErr,
          db
        });

        // Primera clave
        mockInput.write('ValidPasswordFirst123!\n');
        // Segunda clave distinta
        mockInput.write('ValidPasswordSecond456!\n');

        const exitCode = await runPromise;
        assert.equal(exitCode, 1);
        assert.match(errText, /Las contraseñas no coinciden/i);
        assert.equal(errText.includes('ValidPasswordFirst123!'), false);
        assert.equal(errText.includes('ValidPasswordSecond456!'), false);
      } finally {
        db.close();
        if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
      }
    });

    await st.test('C. Flujo exitoso de rotación interactiva CLI con máscara y sin fugas', async () => {
      const mockInput = new MockTtyInputStream();
      const mockOutput = new PassThrough();
      const mockErr = new PassThrough();
      let outText = '';
      let errText = '';
      mockOutput.on('data', (d) => { outText += d.toString(); });
      mockErr.on('data', (d) => { errText += d.toString(); });

      const { db, dbPath } = createIsolatedTestDb('rotation_cli_3.db');
      try {
        createUser({
          name: 'User Success CLI',
          email: 'success_cli@rotation-test.local',
          passwordHash: await hashPassword('InitialPass123!'),
          role: 'ADMIN'
        }, db);

        const runPromise = run(['node', 'script.js', 'success_cli@rotation-test.local'], {
          input: mockInput,
          output: mockOutput,
          errOutput: mockErr,
          db
        });

        // Ingresar clave y confirmación idéntica
        mockInput.write('BrandNewSecurePassword2026!\r');
        mockInput.write('BrandNewSecurePassword2026!\r');

        const exitCode = await runPromise;
        assert.equal(exitCode, 0);
        assert.match(outText, /Contraseña rotada exitosamente/i);
        assert.match(outText, /USER_PASSWORD_ROTATED/);
        // Garantizar que la clave secreta NUNCA apareció ni en stdout ni en stderr
        assert.equal(outText.includes('BrandNewSecurePassword2026!'), false, 'Secret must not be in stdout');
        assert.equal(errText.includes('BrandNewSecurePassword2026!'), false, 'Secret must not be in stderr');
        assert.equal(errText, '', 'stderr must be empty on success');
      } finally {
        db.close();
        if (fs.existsSync(dbPath)) fs.unlinkSync(dbPath);
      }
    });

    await st.test('D. Rechazo estricto de invocación sin TTY o con argumentos extra', async () => {
      const scriptPath = path.join(__dirname, '..', 'scripts', 'rotate-local-user-password.js');

      // 1. Invocación no-TTY
      const noTtyRun = spawnSync(process.execPath, [scriptPath, 'admin@noosadvisory.com'], { encoding: 'utf8' });
      assert.equal(noTtyRun.status, 1);
      assert.match(noTtyRun.stderr, /requiere una sesión interactiva TTY/i);

      // 2. Invocación con argumentos extra (intento de pasar contraseña por línea de comandos)
      const extraArgsRun = spawnSync(process.execPath, [scriptPath, 'admin@noosadvisory.com', '--password=SecretCLI123!'], { encoding: 'utf8' });
      assert.equal(extraArgsRun.status, 1);
      assert.match(extraArgsRun.stderr, /Argumentos inesperados/i);
      assert.equal(extraArgsRun.stdout.includes('SecretCLI123!'), false);
      assert.equal(extraArgsRun.stderr.includes('SecretCLI123!'), false);
    });
  });

  await t.test('10. Comprobación rigurosa de aislamiento de la base de datos real', async () => {
    if (initialRealDbStat && fs.existsSync(CANDIDATE_REAL_DB)) {
      const currentStat = fs.statSync(CANDIDATE_REAL_DB);
      assert.equal(currentStat.mtimeMs, initialRealDbStat.mtimeMs, 'Real database mtime must remain bit-for-bit unchanged');
      assert.equal(currentStat.size, initialRealDbStat.size, 'Real database size must remain bit-for-bit unchanged');
    }
  });
});
